import{i as n,S as g}from"./assets/vendor-5ObWk2rO.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function h(o){return o.map(({webformatURL:i,largeImageURL:e,tags:s,likes:t,views:r,comments:l,downloads:d})=>`
                <li class="gallery-item">
                    <a href="${e}"><img src="${i}" alt="${s}" width="360"/>
                        <ul class="image-descr-list">
                            <li class="image-descr-item">Tags: ${s}</li>
                            <li class="image-descr-item">Likes: ${t}</li>
                            <li class="image-descr-item">Views: ${r}</li>
                            <li class="image-descr-item">Comments: ${l}</li>
                            <li class="image-descr-item">Downloads: ${d}</li>
                        </ul>
                    </a>
                </li>
                `).join("")}const m=document.querySelector(".gallery"),a=document.querySelector(".loader"),f=document.querySelector(".js-search-form");function p(o,i){return fetch(`${o}?${i}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return a.style.visibility="visible",e.json()}).then(e=>{console.log("get:",e),e.hits.length===0&&n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Sorry, there are no images matching your search query. Please try again!"}),m.innerHTML+=h(e.hits),new g(".gallery-item a",{captionDelay:250,captions:!0,captionsData:"alt"}).refresh(),a.style.visibility="hidden"}).catch(e=>n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:`${e}`,message:"Sorry, there are no images matching your search query. Please try again!"})).finally(()=>f.reset())}a.style.visibility="hidden";const y="47534106-2225be5d16534437522f359a0",c=new URLSearchParams({key:y,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0}),b="https://pixabay.com/api/",u=document.querySelector(".js-search-form");u.addEventListener("submit",function(o){o.preventDefault(),m.innerHTML="";const e=o.target.querySelector(".search-input").value.trim();if(console.log("input-trim:",e),!e){n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Please, enter text"}),u.reset();return}console.log("input:",e),c.set("q",e),p(b,c)});
//# sourceMappingURL=index.js.map
